#pragma once
// HTML served from flash. Split into two chunks to stay within WiFiNINA TCP buffers.

static const char HTML_P1[] =
  "<!DOCTYPE html><html><head>"
  "<meta name='viewport' content='width=device-width,initial-scale=1'>"
  "<title>LED</title><style>"
  "*{margin:0;padding:0;box-sizing:border-box}"
  "body{font-family:-apple-system,sans-serif;background:#111;color:#eee;"
        "padding:16px;max-width:460px;margin:auto}"
  "h1{text-align:center;margin-bottom:12px;font-size:1.1rem;color:#aaa}"
  "#pv{height:52px;border-radius:10px;margin-bottom:12px;background:white}"
  ".crd{background:#1c1c1c;border-radius:12px;padding:14px;margin-bottom:10px}"
  ".row{display:flex;gap:8px;margin-bottom:10px}"
  ".btn{flex:1;padding:11px;border:2px solid #333;border-radius:8px;"
        "font-size:.9rem;cursor:pointer;font-weight:600}"
  ".bw{background:#ddd;color:#111}.bc{background:#222;color:#eee}"
  ".on{border-color:#4af!important}"
  ".itm{margin-bottom:8px}.itm:last-child{margin:0}"
  ".lbl{display:flex;justify-content:space-between;font-size:.8rem;"
        "color:#888;margin-bottom:4px}"
  ".lbl b{color:#ccc}"
  "input[type=range]{width:100%;height:6px;-webkit-appearance:none;"
    "appearance:none;border-radius:3px;background:#2a2a2a;"
    "cursor:pointer;display:block;margin:0}"
  "input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;"
    "width:20px;height:20px;border-radius:50%;background:#ddd;cursor:pointer}"
  "</style></head><body>"
  "<h1>LED Control</h1>"
  "<div id='pv'></div>"
  "<div class='crd'>"
    "<div class='row'>"
      "<button class='btn bw' id='bW' onclick=\"M('white')\">White</button>"
      "<button class='btn bc' id='bC' onclick=\"M('color')\">Color</button>"
    "</div>"
    "<div id='dW'>"
      "<div class='itm'>"
        "<div class='lbl'>White Intensity<b id='xW'>255</b></div>"
        "<input type='range' min='0' max='255' value='255' oninput=\"S('w',this,'xW')\">"
      "</div>"
    "</div>"
    "<div id='dC' style='display:none'>"
      "<div class='itm'>"
        "<div class='lbl'>Red<b id='xR'>255</b></div>"
        "<input type='range' min='0' max='255' value='255' oninput=\"S('r',this,'xR')\">"
      "</div>"
      "<div class='itm'>"
        "<div class='lbl'>Green<b id='xG'>255</b></div>"
        "<input type='range' min='0' max='255' value='255' oninput=\"S('g',this,'xG')\">"
      "</div>"
      "<div class='itm'>"
        "<div class='lbl'>Blue<b id='xB'>255</b></div>"
        "<input type='range' min='0' max='255' value='255' oninput=\"S('bl',this,'xB')\">"
      "</div>"
    "</div>"
  "</div>"
  "<div class='crd'>"
    "<div class='itm'>"
      "<div class='lbl'>Brightness<b id='xBr'>128</b></div>"
      "<input type='range' min='0' max='255' value='128' oninput=\"S('br',this,'xBr')\">"
    "</div>"
  "</div>";

static const char HTML_P2[] =
  "<script>"
  "var md='white',W=255,R=255,G=255,B=255,BR=128,tm;"
  "function M(m){"
    "md=m;"
    "document.getElementById('dW').style.display=m=='white'?'':'none';"
    "document.getElementById('dC').style.display=m=='color'?'':'none';"
    "document.getElementById('bW').className='btn bw'+(m=='white'?' on':'');"
    "document.getElementById('bC').className='btn bc'+(m=='color'?' on':'');"
    "fetch('/set?mode='+m).catch(function(){});"
    "P();"
  "}"
  "function S(p,e,id){"
    "var v=parseInt(e.value);"
    "document.getElementById(id).textContent=v;"
    "if(p=='w')W=v;"
    "else if(p=='r')R=v;"
    "else if(p=='g')G=v;"
    "else if(p=='bl')B=v;"
    "else if(p=='br')BR=v;"
    "P();"
    "clearTimeout(tm);"
    "tm=setTimeout(function(){fetch('/set?'+p+'='+v).catch(function(){})},80);"
  "}"
  "function P(){"
    "var el=document.getElementById('pv');"
    "el.style.background=md=='white'?'rgb('+W+','+W+','+W+')':'rgb('+R+','+G+','+B+')';"
    "el.style.opacity=BR/255;"
  "}"
  "M('white');"
  "</script></body></html>";
